# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  # JPA-Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop #alt -> update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Security Configuration
  security:
    user:
      password: bcrypt

  # import additional configs which contain references to environmental variables which need to be set
  config:
    import: classpath:security.yml, mail.yml

# Exception Handling
server:
  error:
    include-stacktrace: never

#SSL config
  port: 8443
  ssl:
    key-alias: server
    key-password: ${SSL_KEY_STORE_PASSWORD}  #Env variable
    key-store: ${PATH-TO_KEYSTORE} #Env variable
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD} #Env variable
    client-auth: none

# Logging Configuration

logging:
  level:
    ua.com.ua.com.associate2coder.authenticationservice: DEBUG
    #org.springframework: DEBUG
    #org.apache.tomcat: DEBUG





